{
 "title": "Gobi Traffic Explorer",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "sampleraddress",
    "label": "SamplerAddress",
    "query": {
     "query": "label_values(gobi_asn_bytes{}, sampleraddress)"
    }
   },
   {
    "name": "srcas",
    "label": "Top100 Src AS",
    "query": {
     "query": "query_result(topk(100, sum by (srcas) (rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\"}[$__range]))))"
    }
   },
   {
    "name": "dstas",
    "label": "Top100 Dst AS",
    "query": {
     "query": "query_result(topk(100, sum by (dstas) (rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\"}[$__range]))))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AS Traffic [Src --> Dst]",
   "type": "timeseries",
   "description": "The overall traffic flowing from selected source AS toward selected destination AS.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__rate_interval]))*8",
     "legendFormat": "bits"
    },
    {
     "expr": "sum(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__rate_interval]))",
     "legendFormat": "packets"
    }
   ]
  },
  {
   "title": "AS Traffic [Src <-- Dst]",
   "type": "timeseries",
   "description": "The overall reverse traffic flowing from selected destination AS toward selected source AS.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__rate_interval]))*8",
     "legendFormat": "bits"
    },
    {
     "expr": "sum(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__rate_interval]))",
     "legendFormat": "packets"
    }
   ]
  },
  {
   "title": "Top10 Destinations [Src --> Dst]",
   "type": "barchart",
   "description": "The Top 10 destination countries of the selected SourceAS/DestAS tuple. Accounts for the whole selected time range.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10,sum by(dstcountry)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__range])))*8",
     "legendFormat": "{{dstcountry}}"
    }
   ]
  },
  {
   "title": "Top10 Destinations [Src <-- Dst]",
   "type": "barchart",
   "description": "The Top 10 destination countries of the selected DestAS/SourceAS tuple (reverse path). Accounts for the whole selected time range.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10,sum by(dstcountry)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__range])))*8",
     "legendFormat": "{{dstcountry}}"
    }
   ]
  },
  { "title": "NextHops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "NextHop [Src --> Dst]",
   "type": "timeseries",
   "description": "The measured data rate by NextHop for traffic flowing from SourceAS toward DestAS.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (nexthop)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__rate_interval])*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NextHop [Src <-- Dst]",
   "type": "timeseries",
   "description": "The measured data rate by NextHop for traffic flowing from DestAS toward SourceAS. (reverse path).",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (nexthop)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__rate_interval])*8)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Protocols", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "L3 Protocols [Src --> Dst]",
   "type": "timeseries",
   "description": "The measured data rate by L3 Protocol for traffic flowing from SourceAS toward DestAS.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(etype)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__rate_interval]))*8",
     "legendFormat": "{{etype}} bits"
    },
    {
     "expr": "sum by (etype)(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__rate_interval]))",
     "legendFormat": "{{etype}} packets"
    }
   ]
  },
  {
   "title": "L3 Protocols [Src <-- Dst]",
   "type": "timeseries",
   "description": "The measured data rate by L3 Protocol for traffic flowing from DestAS toward SourceAS (reverse path).",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(etype)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__rate_interval]))*8",
     "legendFormat": "{{etype}} bits"
    },
    {
     "expr": "sum by (etype)(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__rate_interval]))",
     "legendFormat": "{{etype}} packets"
    }
   ]
  },
  {
   "title": "L4 Protos bits [Src --> Dst]",
   "type": "piechart",
   "description": "The L4 protocols composition of the selected time range from SourceAS toward DestAS (bps).",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(proto)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__range]))*8",
     "legendFormat": "{{proto}} bps"
    }
   ]
  },
  {
   "title": "L4 Protos packets [Src --> Dst]",
   "type": "piechart",
   "description": "The L4 protocols composition of the selected time range from SourceAS toward DestAS (pps).",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(proto)(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__range]))*8",
     "legendFormat": "{{proto}} pps"
    }
   ]
  },
  {
   "title": "L4 Protos bits [Src <-- Dst]",
   "type": "piechart",
   "description": "The L4 protocols composition of the selected time range from DestAS toward SourceAS (reverse path bps).",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(proto)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__range]))*8",
     "legendFormat": "{{proto}} bps"
    }
   ]
  },
  {
   "title": "L4 Protos packets [Src <-- Dst]",
   "type": "piechart",
   "description": "The L4 protocols composition of the selected time range from DestAS toward SourceAS (reverse path pps).",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(proto)(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__range]))*8",
     "legendFormat": "{{proto}} pps"
    }
   ]
  },
  {
   "title": "Top10 Tcp/Udp Dest Ports bits [Src --> Dst]",
   "type": "bargauge",
   "description": "The Top 10 destination ports for the selected time range for traffic flowing from SourceAS toward DestAS (bps).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10,sum by(dstport)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__range])))*8"
    }
   ]
  },
  {
   "title": "Top10 Tcp/Udp Dest Ports bits [Src <-- Dst]",
   "type": "bargauge",
   "description": "The Top 10 destination ports for the selected time range for traffic flowing from DestAS toward SourceAS (reverse path bps).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "topk(10,sum by(dstport)(rate(gobi_asn_bytes{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__range])))*8"
    }
   ]
  },
  {
   "title": "Top10 Tcp/Udp Dest Ports packets [Src --> Dst]",
   "type": "bargauge",
   "description": "The Top 10 destination ports for the selected time range for traffic flowing from SourceAS toward DestAS (pps).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10,sum by(dstport)(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$srcas\", dstas=~\"$dstas\"}[$__range])))*8"
    }
   ]
  },
  {
   "title": "Top10 Tcp/Udp Dest Ports packets [Src <-- Dst]",
   "type": "bargauge",
   "description": "The Top 10 destination ports for the selected time range for traffic flowing from DestAS toward SourceAS (reverse path pps).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "topk(10,sum by(dstport)(rate(gobi_asn_packets{sampleraddress=~\"$sampleraddress\", srcas=~\"$dstas\", dstas=~\"$srcas\"}[$__range])))*8"
    }
   ]
  }
 ]
}