{
 "title": "Gobi Internals",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "DB Cardinality",
   "type": "timeseries",
   "description": "The number of series of Gobi metrics.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (__name__)({__name__=\"gobi_asn_bytes\"})",
     "legendFormat": "Number of series"
    }
   ]
  },
  {
   "title": "Untracked Traffic",
   "type": "timeseries",
   "description": "The rate of traffic below the minimum configured data rate.\nThe percentage of this traffic against the whole monitored traffic.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(gobi_asn_untracked_bytes{}[$__rate_interval]))*8",
     "legendFormat": "Untracked traffic"
    },
    {
     "expr": "100*sum(rate(gobi_asn_untracked_bytes{}[$__rate_interval]))/sum(rate(gobi_asn_bytes{}[$__rate_interval]))",
     "legendFormat": "% of total traffic"
    }
   ]
  },
  {
   "title": "Gobi Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_sys_bytes{job=\"gobi\"})",
     "legendFormat": "Allocated memory"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_sys_bytes{job=\"gobi\"})",
     "legendFormat": "Heap reserved"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_inuse_bytes{job=\"gobi\"})",
     "legendFormat": "Heap in use"
    }
   ]
  },
  {
   "title": "GoFlow2 Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_sys_bytes{job=\"goflow2\"})",
     "legendFormat": "Allocated memory"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_sys_bytes{job=\"goflow2\"})",
     "legendFormat": "Heap reserved"
    },
    {
     "expr": "avg by (job)(go_memstats_heap_inuse_bytes{job=\"goflow2\"})",
     "legendFormat": "Heap in use"
    }
   ]
  },
  {
   "title": "NetFlow Ingress Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_flowset_records_sum[$__rate_interval]))",
     "legendFormat": "NetFlow packet rate"
    }
   ]
  },
  {
   "title": "NetFlow Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum(rate(flow_process_nf_errors_count[$__rate_interval])) by (error)",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}