global:
  scrape_interval:     60s
  scrape_timeout:      10s

scrape_configs:
  - job_name: "prom"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gobi"
    static_configs:
      - targets: ["gobi:9310"]

  - job_name: "goflow2"
    static_configs:
      - targets: ["172.22.99.1:9311"]
