apiVersion: 1

datasources:
 - name: Prometheus
   type: prometheus
   access: proxy
   orgId: 1
   url: http://prometheus:9090
   isDefault: true
   uid: gobi_unique_uid
   jsonData:
     timeInterval: '60s'
   version: 1
   editable: true