name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+**

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Project
        run: |
          GOOS=linux GOARCH=amd64 make build
          GOOS=linux GOARCH=arm64 make build
          GOOS=darwin GOARCH=amd64 make build
          GOOS=darwin GOARCH=arm64 make build

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/*

  build-docker:
    name: Release-Docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{github.repository}}
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{raw}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
